package sayfalar;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;


/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class EkranSonuc extends Panel
{
    protected Image		  imageYsrSearch;
    protected Button		  butonAnaSayfa;
    protected TextField		  aramaAlaniSS;
    protected Button		  buttonSearchSS;
    protected Button		  buttonSearchOnPageSS;
    protected TabSheet		  tabSheet;
    protected AbsoluteLayout	  tabAll;
    protected Panel		  panelAll;
    protected VerticalLayout	  sfAll;
    protected VerticalLayout	  sonuc;
    protected Link		  link;
    protected Label		  labelUrl;
    protected Label		  labelIcerik;
    protected VerticalLayout	  sonuc1;
    protected Link		  link1;
    protected Label		  labelUrl1;
    protected Label		  labelIcerik1;
    protected VerticalLayout	  sonuc2;
    protected Link		  link2;
    protected Label		  labelUrl2;
    protected Label		  labelIcerik2;
    protected VerticalLayout	  sonuc3;
    protected Link		  link3;
    protected Label		  labelUrl3;
    protected Label		  labelIcerik3;
    protected VerticalLayout	  sonuc4;
    protected Link		  link4;
    protected Label		  labelUrl4;
    protected Label		  labelIcerik4;
    protected VerticalLayout	  sonuc5;
    protected Link		  link5;
    protected Label		  labelUrl5;
    protected Label		  labelIcerik5;
    protected VerticalLayout	  sonuc6;
    protected Link		  link6;
    protected Label		  labelUrl6;
    protected Label		  labelIcerik6;
    protected VerticalLayout	  sonuc7;
    protected Link		  link7;
    protected Label		  labelUrl7;
    protected Label		  labelIcerik7;
    protected VerticalLayout	  sonuc8;
    protected Link		  link8;
    protected Label		  labelUrl8;
    protected Label		  labelIcerik8;
    protected VerticalLayout	  sonuc9;
    protected Link		  link9;
    protected Label		  labelUrl9;
    protected Label		  labelIcerik9;
    protected GridLayout	  tabImages;
    protected AbsoluteLayout	  tabSearchOnPage;
    protected Label		  onPageSonuc;
    protected Panel		  tabPage_URL_Rank;
    protected Grid<main.BenimURL> gridUrlRank;
    protected Panel		  tabWebSiteRank;
    protected Grid		  gridWebSiteRank;
    protected Panel		  tabSemanticRank;
    protected AbsoluteLayout	  panelDosyaAl;
    protected Image		  drag_drop;
    
    
    public EkranSonuc()
    {
	Design.read(this);
    }
}
