package sayfalar;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Image;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;


/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class EkranGiris extends AbsoluteLayout
{
    protected Image	arkaPlan;
    protected Button	buttonUrlGir;
    protected Button	buttonSearchOnPage;
    protected Button	buttonSearchURL;
    protected Button	buttonSearchSite;
    protected Button	buttonSearchSemantik;
    protected Image	ysrSearch;
    protected TextField	aramaAlani;
    protected Button	buttonSearch;
    protected Button	buttonChangeLeft;
    protected Button	buttonChangeRight;
    
    
    public EkranGiris()
    {
	Design.read(this);
    }
}
